### ISSUE TITLE
Cannot compile on Node v0.11.11-release MacOSX Mavericks

### ISSUE THREAD

**Issue by sonewman** [dhruvbird/http-sync#27]
This fails on node-gyp rebuild:

```
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.0
gyp info using node@0.11.11 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sam/code/fsp-app/node/node_modules/http-sync/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sam/.node-gyp/0.11.11/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/sam/.node-gyp/0.11.11',
gyp info spawn args   '-Dmodule_root_dir=/Users/sam/code/fsp-app/node/node_modules/http-sync',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/curllib/curllib.o
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:109:1: error: unknown type name 'clock_t'; did you mean 'node::clock_t'?
clock_t clock(void) __DARWIN_ALIAS(clock);
^
/usr/include/sys/_types/_clock_t.h:30:33: note: 'node::clock_t' declared here
typedef __darwin_clock_t        clock_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:110:19: error: unknown type name 'time_t'; did you mean 'node::time_t'?
char *ctime(const time_t *);
                  ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:111:17: error: unknown type name 'time_t'; did you mean 'node::time_t'?
double difftime(time_t, time_t);
                ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:111:25: error: unknown type name 'time_t'; did you mean 'node::time_t'?
double difftime(time_t, time_t);
                        ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:113:25: error: unknown type name 'time_t'; did you mean 'node::time_t'?
struct tm *gmtime(const time_t *);
                        ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:114:28: error: unknown type name 'time_t'; did you mean 'node::time_t'?
struct tm *localtime(const time_t *);
                           ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:115:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t mktime(struct tm *) __DARWIN_ALIAS(mktime);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:118:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t time(time_t *);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:118:13: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t time(time_t *);
            ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:126:21: error: unknown type name 'time_t'; did you mean 'node::time_t'?
char *ctime_r(const time_t *, char *);
                    ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:127:27: error: unknown type name 'time_t'; did you mean 'node::time_t'?
struct tm *gmtime_r(const time_t * __restrict, struct tm * __restrict);
                          ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:128:30: error: unknown type name 'time_t'; did you mean 'node::time_t'?
struct tm *localtime_r(const time_t * __restrict, struct tm * __restrict);
                             ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:131:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t posix2time(time_t);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:131:19: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t posix2time(time_t);
                  ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:136:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t time2posix(time_t);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:136:19: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t time2posix(time_t);
                  ^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:137:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t timelocal(struct tm * const);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:56:
/usr/include/time.h:138:1: error: unknown type name 'time_t'; did you mean 'node::time_t'?
time_t timegm(struct tm * const);
^
/usr/include/sys/_types/_time_t.h:30:26: note: 'node::time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from ../curllib.cc:11:
In file included from /usr/include/curl/curl.h:82:
In file included from /usr/include/sys/time.h:193:
/usr/include/sys/_select.h:39:18: error: unknown type name 'fd_set'; did you mean 'node::fd_set'?
int      select(int, fd_set * __restrict, fd_set * __restrict,
                     ^
/usr/include/sys/_types/_fd_def.h:48:3: note: 'node::fd_set' declared here
} fd_set;
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/curllib/curllib.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:879:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/sam/code/fsp-app/node/node_modules/http-sync
gyp ERR! node -v v0.11.11
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
```

**Comment by EndangeredMassa** [comment]
0.12 stable has since been released and we're moving forward into (iojs) 3.0.0+. Should we close this?
